#
# Makefile for the harman drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SPI_DAB_PLUGIN)   += dabplugin/
obj-$(CONFIG_SPI_DYNAMIC_NODE) += dynamic_spi_node/
obj-$(CONFIG_HARMAN_LVSD)      += lvsd/
